apiVersion: apps/v1
kind: Deployment 
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver    
  replicas: 5
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "brunomarins/hello-go:v1.2"
          volumeMounts:
            - mountPath: "/config"
              name: config-volume

          resources:
            requests: 
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi
      volumes:
        - name: config-volume        
          configMap:
            name: goserver-env
            items:
            - key: config
              path: "config.txt"