apiVersion: apps/v1
kind: Deployment 
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver    
  replicas: 5
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "brunomarins/hello-go:v6"
          env: 
            - name: ENV1
              value: "ENV1"
            - name: ENV2
              value: "ENV2"