apiVersion: apps/v1
kind: Deployment 
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver    
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "brunomarins/hello-go:v2.6"   

          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 30            

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1            

                      

          volumeMounts:
            - mountPath: "/config"
              name: config-volume

          resources:
            requests: 
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi

          envFrom:
            - configMapRef:
                name: goserver-env                
            - secretRef:
                name: goserver-secret
      volumes:
        - name: config-volume        
          configMap:
            name: goserver-config-volume
            items:
            - key: config
              path: "config.txt"