apiVersion: apps/v1
kind: Deployment 
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver    
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "wesleywillians/hello-go:v9.6"        

          resources:
            requests:
              cpu: 100m
              memory: 10Mi
            limits:
              cpu: 500m
              memory: 20Mi

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 10                    
          volumeMounts:
            - mountPath: "/config"
              name: config-volume
              
          envFrom:
            - configMapRef:
                name: goserver-env                
            - secretRef:
                name: goserver-secret
      volumes:
        - name: config-volume        
          configMap:
            name: goserver-config-volume
            items:
            - key: config
              path: "config.txt"