apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  type: NodePort
  selector:
    app: goserver  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30005  
  
